name: "Hassio Proton Drive Backup"
description: "Backup your homeassistant data to Proton Drive"
version: "1.0.0"
slug: "hassio_proton_drive_backup"
init: false
arch:
  - aarch64
  - amd64 
hassio_api: true
hassio_role: "backup"
ingress: true
map:
  - backup:rw
options:
  backup_directory: "Home Assistant Backups"
  log_level: Info
  proton_drive_user: null
  proton_drive_password: null
schema:
  backup_directory: str
  log_level: match(Info|Debug|Warn|Error)
  proton_drive_user: str
  proton_drive_password: password